website/peoria/urls.py
from django.conf.urls import url
from . import views




app_name='peoria'



urlpatterns = [
    #/peoria/
    url(r'^$', views.home, name='home'),
    url(r'^trash/$', views.trash, name='trash'),

    # /nfw/gripe/
    url(r'^gripe/$', views.GripeList.as_view(), name='gripe-list'),
    url(r'^gripe/create/$', views.GripeCreate2, name='gripe-create'),
    url(r'^gripe/(?P<pk>[0-9]+)/$', views.GripeDetail.as_view(), name='gripe-detail'),
    url(r'^gripe/(?P<pk>[0-9]+)/update/$', views.GripeUpdate.as_view(), name='gripe-update'),
    url(r'^gripe/(?P<pk>[0-9]+)/delete/$', views.GripeDelete.as_view(), name='gripe-delete'),
    url(r'^gripe/(?P<pk>[0-9]+)/upvote/$', views.GripeUpvote, name='gripe-upvote'),

    # /nfw/project/
    url(r'^project/$', views.ProjectList.as_view(), name='project-list'),
#    url(r'^project/create/$', views.ProjectCreate.as_view(), name='project-create'),
    url(r'^project/create/$', views.ProjectCreate2, name='project-create'),

    url(r'^project/(?P<pk>[0-9]+)/$', views.ProjectDetail.as_view(), name='project-detail'),
    url(r'^project/(?P<pk>[0-9]+)/update/$', views.ProjectUpdate.as_view(), name='project-update'),
    url(r'^project/(?P<pk>[0-9]+)/delete/$', views.ProjectDelete.as_view(), name='project-delete'),

    url(r'^chris/$', views.Chris, name='chris'),
]

website/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^peoria/', include('peoria.urls')),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

website/peoria/models.py
from django.db import models
from datetime import date, datetime
from django.core.urlresolvers import reverse




class Gripe(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField()
    votes = models.IntegerField(default=0)
    latitude = models.DecimalField(max_digits=10, decimal_places=6, default=40.703545)
    longitude = models.DecimalField(max_digits=10, decimal_places=6, default=-89.579086)



    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('peoria:gripe-detail', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['-votes']



class Project(models.Model):
    latitude = models.DecimalField(max_digits=10, decimal_places=6, default=40.703545)
    longitude = models.DecimalField(max_digits=10, decimal_places=6, default=-89.579086)

    PAVEMENT = 'PV'
    BIKE = 'BK'
    TRASHCANS = 'TC'
    RAMPS = 'RA'
    SIDEWALKS = 'SW'
    TYPE_CHOICES = (
        (PAVEMENT, 'Pavement'),
        (BIKE, 'Bike'),
        (TRASHCANS, 'Trashcans'),
        (RAMPS, 'Ramps'),
        (SIDEWALKS, 'Sidewalks'),
    )
    type = models.CharField(max_length=100, choices=TYPE_CHOICES)
    filename = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.type + str(self.pk)

    def get_absolute_url(self):
        return reverse('peoria:project-detail', kwargs={'pk':self.pk})

website/peoria/forms.py
from django import forms
from .models import Project, Gripe


class ProjectGeo(forms.ModelForm):
    address = forms.CharField(max_length=200)

    class Meta:
        model = Project
        fields = ['type',
                  'description',]


class GripeGeo(forms.ModelForm):

    class Meta:
        model = Gripe
        fields = ['name',
                  'address',
                  'description',]

website/peoria/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Gripe, Project

from .forms import ProjectGeo, GripeGeo



from geopy.geocoders import Nominatim



def Chris(request):
    return render(request, 'peoria/chris.html')




def home(request):
    myPavementProjects = Project.objects.filter(type='PV')
    myBikeProjects = Project.objects.filter(type='BK')
    myTrashCanProjects = Project.objects.filter(type='TC')
    myRampsProjects = Project.objects.filter(type='RA')
    mySideWalkProjects = Project.objects.filter(type='SW')



    context = {'myPavementProjects': myPavementProjects,
               'myBikeProjects': myBikeProjects,
               'myTrashCanProjects':myTrashCanProjects,
               'myRampsProjects':myRampsProjects,
               'mySideWalkProjects':mySideWalkProjects,
               }
    return render(request, 'peoria/home2.html', context)

def trash(request):
    return(render(request, 'peoria/trash.html'))


class GripeList(generic.ListView):
    template_name = 'peoria/gripe-list.html'
    context_object_name = 'gripe_list'

    def get_queryset(self):
        return Gripe.objects.all()

class GripeDetail(generic.DetailView):
    model = Gripe
    template_name = 'peoria/gripe-detail.html'


class GripeCreate(CreateView):
    model = Gripe
    fields = ['name',
              'address',
              'description',
    ]


class GripeUpdate(UpdateView):
    model = Gripe
    fields = ['name',
              'address',
              'description',
              'latitude',
              'longitude',
              ]

class GripeDelete(DeleteView):
    model = Gripe
    success_url = reverse_lazy('peoria:gripe-list')

def GripeUpvote(request, pk):
    try:
        selected_gripe = Gripe.objects.get(pk=pk)
    except (KeyError, Gripe.DoesNotExist):
        return HttpResponse("Error, gripe does not exist")
    else:
        mynum = selected_gripe.votes
        selected_gripe.votes = mynum + 1
        selected_gripe.save()

        return HttpResponseRedirect(reverse('peoria:gripe-list'))



class ProjectList(generic.ListView):
    template_name = 'peoria/project-list.html'
    context_object_name = 'project_list'

    def get_queryset(self):
        return Project.objects.all()


class ProjectDetail(generic.DetailView):
    model = Project
    template_name = 'peoria/project-detail.html'


class ProjectCreate(CreateView):
    model = Project
    fields = ['latitude',
              'longitude',
              'type',
              'description',
    ]


class ProjectUpdate(UpdateView):
    model = Project
    fields = ['latitude',
              'longitude',
              'type',
              'description',
    ]



class ProjectDelete(DeleteView):
    model = Project
    success_url = reverse_lazy('peoria:project-list')



def ProjectCreate2(request):
    if request.method == 'POST':
        form = ProjectGeo(request.POST)
        if form.is_valid():
            myAddress = form.cleaned_data['address']
            myType = form.cleaned_data['type']
            myDescription = form.cleaned_data['description']
            geolocator = Nominatim()
            location = geolocator.geocode(myAddress)
            myLatitude = location.latitude
            myLongitude = location.longitude
            a = Project(latitude=myLatitude,
                        longitude=myLongitude,
                        type=myType,
                        description=myDescription,
                        )
            a.save()
        return HttpResponseRedirect(reverse('peoria:project-list'))

    else:
        form = ProjectGeo
        return render(request, 'peoria/project-create.html', {'form':form})



def GripeCreate2(request):
    if request.method == 'POST':
        form = GripeGeo(request.POST)
        if form.is_valid():
            myName = form.cleaned_data['name']
            myAddress = form.cleaned_data['address']
            myDescription = form.cleaned_data['description']
            geolocator = Nominatim()
            location = geolocator.geocode(myAddress)
            myLatitude = location.latitude
            myLongitude = location.longitude
            a = Gripe(name=myName,
                      address=myAddress,
                      description=myDescription,
                      latitude=myLatitude,
                      longitude= myLongitude,
                      )
            a.save()
        return HttpResponseRedirect(reverse('peoria:gripe-list'))

    else:
        form = GripeGeo
        return render(request, 'peoria/gripe-create.html', {'form':form})

website/peoria/templates/peoria/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Peoria!!!
        {% endblock %}
    </title>

    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'peoria/style.css' %}" />
</head>


<nav class="navbar-inverse">
    <div class="container-fluid">
        <!--- Logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'peoria:home' %}" >Peoria 0.1</a>
        </div>

        <!--- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">

                <li class="" >
                    <a href="{% url 'peoria:project-list' %}">
                        <span class="glyphicon glyphicon-tag"></span> Projects
                    </a>
                </li>

                <li class="" >
                    <a href="{% url 'peoria:gripe-list' %}">
                        <span class="glyphicon glyphicon-tag"></span> Gripes
                    </a>
                </li>

                <li class="" >
                    <a href="{% url 'peoria:trash' %}">
                        <span class="glyphicon glyphicon-tag"></span> Trash
                    </a>
                </li>




            </ul>
        </div>
    </div>
</nav>




	<script src="//d3js.org/d3.v3.min.js"></script>









<body>
{% block body %}
{% endblock %}
</body>

<!-- Footer -->
   <footer>
       <div class="container text-center">
           <p><a href="https://xd.adobe.com/view/f6c99c6b-420c-4b9a-ac0c-693a7c73246a/" target="blank_">Copyright</a> &copy; 2017 desig|n&#275| Urban Unicorns - All Rights Reserved.</p>
       </div>
   </footer>

website/peoria/templates/peoria/chris.html
{% extends 'peoria/base.html' %}
{%  block body %}

{% load static %}


    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #legend {
        font-family: Arial, sans-serif;
        background: #fff;
        padding: 10px;
        margin: 10px;
        border: 3px solid #000;
      }
      #legend h3 {
        margin-top: 0;
      }
      #legend img {
        vertical-align: middle;
      }
      #floating-panel {
        position: absolute;
        top: 10px;
        left: 25%;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
        text-align: center;
        font-family: 'Roboto','sans-serif';
        line-height: 30px;
        padding-left: 10px;
      }
    </style>





  <body>
    <div id="floating-panel">
      <input id="address" type="textbox" value="Peoria, IL">
      <input id="submit" type="button" value="Geocode">
    </div>
    <div id="map"></div>
    <script>
      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 11,
          center: {lat: 40.6733, lng: -89.5990}
        });
        var geocoder = new google.maps.Geocoder();

        document.getElementById('submit').addEventListener('click', function() {
          geocodeAddress(geocoder, map);
        });
      }

      function geocodeAddress(geocoder, resultsMap) {
        var address = document.getElementById('address').value;
        geocoder.geocode({'address': address}, function(results, status) {
          if (status === 'OK') {
            resultsMap.setCenter(results[0].geometry.location);

	    resultsMap.data.loadGeoJson("{% static 'peoria/chris_data.geojson' %}");

            var marker = new google.maps.Marker({
              map: resultsMap,
              position: results[0].geometry.location
            });


          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCMfQpSfvUYKBjeJ2Mf0i5JJl4gjrAC19w&callback=initMap">
    </script>
  </body>








{% endblock %}

website/peoria/templates/peoria/form-template.html
<!-- model fields come in list called form-->
{% for field in form %}
    <div class="form-group">
        <div class = "col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

website/peoria/templates/peoria/gripe-create.html
{% extends 'peoria/base.html' %}
{%  block body %}



<form action="" method="post">
    {%  csrf_token %}
        {% include 'peoria/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>



{% endblock %}

website/peoria/templates/peoria/gripe-detail.html
{% extends 'peoria/base.html' %}
{%  block body %}

Gripe Detail

    <h1>{{ object }}</h1>

    <h2>{{ object.description }}</h2>

    <a href = "{%  url 'peoria:gripe-update' object.id %}">Edit</a>
    <a href = "{%  url 'peoria:gripe-delete' object.id %}">Delete</a>


{% endblock %}

website/peoria/templates/peoria/gripe-list.html
{% extends 'peoria/base.html' %}
{%  block body %}

    <h1>Gripe List</h1>









<div class="container">

        <a href="{% url 'peoria:gripe-create' %}">
        <span class="glyphicon glyphicon-plus"></span>Create New Gripe
    </a>

</div>



    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Upvote</th>
                <th>Name</th>
                <th>Description</th>
                <th>Address</th>
                <th>Votes</th>
            </tr>
        </thead>
        <tbody>
            {% for gripe in gripe_list %}
                <tr>
                    <td>
<a href = "{%  url 'peoria:gripe-upvote' gripe.pk %}">Upvote!</a>


                    </td>
                    <td><a href="{% url 'peoria:gripe-detail' gripe.id %}">{{ gripe.name }}</td>
                    <td>{{ gripe.description }}</td>
                    <td>{{ gripe.address }}</td>
                    <td>{{ gripe.votes }}</td>

                </tr>


            {% endfor %}

        </tbody>
    </table>





{% endblock %}

website/peoria/templates/peoria/gripe_confirm_delete.html
{% extends 'peoria/base.html' %}
{% block body %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock %}

website/peoria/templates/peoria/gripe_form.html
{% extends 'peoria/base.html' %}
{% block  title %} Gripe Form {% endblock %}
{% block body %}
    <h2> Gripe Form </h2>
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'peoria/form-template.html' %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
{% endblock %}

website/peoria/templates/peoria/home.html
{% extends 'peoria/base.html' %}


{% block title %}
Peoria Home
{% endblock %}





{% block body %}
    <h1>Peoria HOME 0.1</h1>
    Hello, welcome to Peoria website!!!</br>
    Go Urban Unicorns!!!


    <h2>
    <a href = "{%  url 'peoria:gripe-list' %}">Submit your gripe!!!</a>
    </h2>



    <iframe width="600" height="450" frameborder="0" style="border:0"
            src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJrXlYU1xZCogR24B9azL0-8o&key=AIzaSyAYEjsF90Cthd2KilWY9lS96vXC3I1M7wg"
            allowfullscreen></iframe>



<div id="map"></div>
    <script>

      function initMap() {
        var myLatLng = {lat: 40.7, lng: -89.6};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 4,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYEjsF90Cthd2KilWY9lS96vXC3I1M7wg&callback=initMap">
    </script>






{% endblock %}

website/peoria/templates/peoria/home2.html
{% extends 'peoria/base.html' %}


{% block title %}
Peoria Home
{% endblock %}

{% block body %}

    {% load static %}


<html>
  <head>
    <style>
       #map {
        height: 500px;
        width: 100%;
        align-self: center;
       }
    </style>

  </head>


<body>

  <div class="jumbotron text-center">
    <img src="{% static "peoria/images/logo.png" %}" alt="My image"/>
    <h1>Build Peoria</h1>
    <p>Infrastructure is the new sexy.</p>
  </div>


  <div class="container text-center">
    <div class="row">
      <div class="col-sm-4">
        <img src="{% static "peoria/images/infras1_1.png" %}" alt="My image"/>
        <h3>Maps of Infrastructure</h3>
        <p>Here you can find what is going on in Peoria.</p>
        <p>Have fun zooming!</p>
        <a href="#" class="btn btn-info" role="button">Link Button</a>
      </div>
      <div class="col-sm-4">
        <img src="{% static "peoria/images/infras2.png" %}" alt="My image"/>
        <h3>Peoria Cares</h3>
        <p>Tell us what we need to work on.</p>
        <p>Upload a picture as well.</p>
        <a href="{%  url 'peoria:gripe-list' %}" class="btn btn-info" role="button">Submit your Gripes!</a>

      </div>
      <div class="col-sm-4">
        <img src="{% static "peoria/images/infras3.png" %}" alt="My image"/>
        <h3>Rate that Infrastructure</h3>
        <p>Up-vote your favorite infrastructure projects.</p>
        <p>The hottest ones are going to be our priorities.</p>
        <a href="#" class="btn btn-info" role="button">Link Button</a>
      </div>
    </div>
  </div>

    <div class="container text-center">
      <div class="row">
        <div class="col-">
    <h3>Peoria Infrastructure Projects </h3>
    <div id="map"></div>
        </div>
      </div>
    </div>


<!--ACCOUNT SIGN UP-->
<div class="bg-primary container text-center">
  <h2>Account Information for Build Peoria </h2>
<div class="row">
    <form action="/action_page.php">
      <div class="col-xs-4">
      <label for="name">Name:</label>
        <input type="email" class="form-control" id="email" placeholder="Enter name" name="name">
      </div>
      <div class="col-xs-4">
      <label for="email">Email:</label>
        <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
      </div>
      <div class="col-xs-4">
      <label for="pwd">Password:</label>
        <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pwd">
      </div>
      <div class="col-xs-4">
      <label for="Home Address">Home Address:</label>
        <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pwd">
      </div>
      <div class="col-xs-4">
      <label for="Work Address">Work Address:</label>
        <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pwd">
      </div>
</div>
<div class="row text-center">
      <div class="checkbox">
        <label><input type="checkbox" name="remember"> Remember me</label>
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
  </div>
</div>

<div class="container text-center">
<h1>Who are you?</h1>
<form action="/action_page.php" method="get">
  <input type="checkbox" name="CitizenType" value="Resident"> Peoria Resident<br>
  <input type="checkbox" name="CitizenType" value="BusinessOwner" > Business Owner<br>
    <input type="checkbox" name="CitizenType" value="AreaVisitor" > Visitor to Peoria <br>
  <button type="submit" class="btn btn-default" value="Submit">Submit</button>
</form>
</div>

<div class="container text-center">
<h1>How do you roll?</h1>
<form action="/action_page.php" method="get">
  <input type="checkbox" name="Howtheyroll" value="Car"> Car <br>
  <input type="checkbox" name="Howtheyroll" value="Public Transit" > Public Transit<br>
    <input type="checkbox" name="Howtheyroll" value="Walk/Bike" > Walking/Biking <br>
  <button type="submit" class="btn btn-default" value="Submit">Submit</button>
</form>
</div>



<!--SCRIPT-->
    <script>



        function initMap() {

        var uluru = {lat: 40.6936, lng: -89.5890};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: uluru
        });


        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });




            {% for project in myPavementProjects  %}
                var marker = new google.maps.Marker({
                position: {lat:{{ project.latitude }} , lng:{{ project.longitude }} },
                label: 'pavement project',
                map: map,
                icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png',
        });
            {% endfor %}


            {% for project in myBikeProjects  %}
                var marker = new google.maps.Marker({
                position: {lat:{{ project.latitude }} , lng:{{ project.longitude }} },
                label: 'bike project',
                map: map,
                icon: 'http://maps.google.com/mapfiles/ms/icons/green-dot.png',
        });
            {% endfor %}

            {% for project in myTrashCanProjects  %}
                var marker = new google.maps.Marker({
                position: {lat:{{ project.latitude }} , lng:{{ project.longitude }} },
                label: 'trashcan project',
                map: map,
                icon: 'http://maps.google.com/mapfiles/ms/icons/yellow-dot.png',

        });
            {% endfor %}


            {% for project in myRampsProjects  %}
                var marker = new google.maps.Marker({
                position: {lat:{{ project.latitude }} , lng:{{ project.longitude }} },
                label: 'ramp project',
                map: map,
                icon: 'http://maps.google.com/mapfiles/ms/icons/red-dot.png',

        });
            {% endfor %}


            {% for project in mySideWalkProjects  %}
                var marker = new google.maps.Marker({
                position: {lat:{{ project.latitude }} , lng:{{ project.longitude }} },
                label: 'sidewalk project',
                map: map,
                icon: 'http://maps.google.com/mapfiles/ms/icons/orange-dot.png',

        });
            {% endfor %}



      }




    </script>




    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYEjsF90Cthd2KilWY9lS96vXC3I1M7wg&callback=initMap">
    </script>
  </body>
</html>






{% endblock %}

website/peoria/templates/peoria/project-create.html
{% extends 'peoria/base.html' %}
{%  block body %}



<form action="" method="post">
    {%  csrf_token %}
        {% include 'peoria/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>



{% endblock %}

website/peoria/templates/peoria/project-detail.html
{% extends 'peoria/base.html' %}
{%  block body %}

Gripe Detail

    <h1>{{ object }}</h1>

    <h2>{{ object.description }}</h2>

    <a href = "{%  url 'peoria:project-update' object.id %}">Edit</a>
    <a href = "{%  url 'peoria:project-delete' object.id %}">Delete</a>


{% endblock %}

website/peoria/templates/peoria/project-list.html
{% extends 'peoria/base.html' %}
{%  block body %}

    <h1>!City Goverment Access Only!</h1>


<div class="container">

        <a href="{% url 'peoria:project-create' %}">
        <span class="glyphicon glyphicon-plus"></span>Create New Project
    </a>

</div>



    <table class="table table-bordered">
        <thead>
            <tr>
                <th>latitude</th>
                <th>longitude</th>
                <th>type</th>
                <th>filename</th>
                <th>description</th>
            </tr>
        </thead>
        <tbody>
            {% for project in project_list %}
                <tr>
                    <td>{{ project.latitude }}</td>
                    <td>{{ project.longitude }}</td>
                    <td>{{ project.type }}</td>
                    <td>{{ project.filename }}</td>
                    <td>{{ project.description }}</td>

                </tr>


            {% endfor %}

        </tbody>
    </table>





{% endblock %}

website/peoria/templates/peoria/trash.html
{% extends 'peoria/base.html' %}


{% block title %}
Peoria Trash Cans
{% endblock %}




{% load static %}
{% block body %}
    <h3>Things to gripe about - not enough trash cans on your bus route</h3>
       <script>
            
                var width = 1050,
                   height  = 1000,
                   format = d3.format(",d"),
                   color = d3.scale.category20b(); 
               
               //choosing the correct padding is crucial because the game titles 
               //are so long they are over the top of each other
               var bubble = d3.layout.pack()
                   .sort(null)
                   .size([width, height])
                   .padding(80);
               var svg = d3.select("body")
                   .append("svg")
                   .attr("width", width)
                   .attr("height", height)
                   .attr("class", "bubble");
           
               //adding some random movement
                var movement = d3.random.normal();
        
                
                //colors of the bubbles will be inside this color scale depending on 
                //the number of games sold
                var color = d3.scale.linear()
                    .domain([0,10])
                    .range(["red", "blue"]);
                    
                    
                //Takes the square root so the area is reflective of the underlying
                //relationship between the amount of video games
                var size = d3.scale.sqrt()
                        .domain([0,35])
                        .range([0,35]);
                
                
        d3.csv("{% static 'peoria/busRoute.csv'%}", function(error, data){
                if (error) throw error;
                //convert numerical values from strings to numbers
                data = data.map(function(d){ d.value = parseFloat(d.Amount); return d; });
                //bubbles needs very specific format, convert data to this.
                var nodes = bubble.nodes({children:data}).filter(function(d) { return !d.children; });
                //automatically creates the g svg element
                //.enter() because it is more data elements than dom elements
                var bubbles = svg.append("g")
                    .attr("transform", "translate(0,0)")
                    .selectAll(".bubble")
                    .data(nodes)
                    .enter();
                //create the bubbles
                //need to take the squareroot from the size scale,
                //cause the area is pi*r^2
                //color is also a function of a scale.
                bubbles.append("circle")
                    .attr("r", function(d){ return size(d.value); })
                    .attr("cx", function(d){ return d.x - 30; })
                    .attr("cy", function(d){ return d.y - 30; })
                    .style("fill", function(d) { return color(d.value); })
                    .transition()
                        .duration(2000)
                        .attr("cx", function(d){ return d.x + movement(5,5); })
                        .attr("cy", function(d){ return d.y + movement(5,5); });
                //format the text for each bubble
                //Adds the name of each text
                bubbles.append("text")
                    .attr("x", function(d){ return d.x ; })
                    .attr("y", function(d){ return d.y - 32  ; })
                    .attr("text-anchor", "middle")
                    .text(function(d){return (d.Name + ": " + (d.value));})
                    .style({
                        "fill":"black", 
                        "font-family":"Helvetica Neue, Helvetica, Arial, san-serif",
                        "font-size": "11px"
                    })
                    .transition()
                        .duration(2000)
                        .attr("x", function(d){ return d.x + movement(5,5); });
        });
            
            
        </script>
    <h2>
    <a href = "{%  url 'peoria:gripe-list' %}">Submit your gripe!!!</a>
    </h2>



{% endblock %}